
export const HOME = {
    GET_HERO_MODEL: 'HOME/GET_HERO_MODEL',
    SET_HERO_MODEL: 'HOME/SET_HERO_MODEL',
};

export const FAQ = {
    GET_MODEL: 'FAQ/GET_MODEL',
    SET_MODEL: 'FAQ/SET_MODEL',
    SET_ACTIVE_ARTICLE: 'FAQ/SET_ACTIVE_ARTICLE'
};